# This is the configuration used to check the rubocop source code.

Style/Encoding:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/*'
    - '*.gemspec'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

#Metrics/CyclomaticComplexity:
#  Max: 8
